### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by OljasOmar** [Open-SL/Chords-Transposer#10]
Hi, first of all, I would like to thank you for this script. I am not good at programming unfortunately. Could you please tell me how to automatically parse content from website and transpose chords dynamically, not by text area. Thank you

**Comment by nadunindunil** [comment]
Hi @OljasOmar, Chords transporser is pretty straight forward to use.
you can find minified js code inside dist folder (chords.js). What you have to do is pass a your string into a function as described in readme

```
  shiftScale(src, from, to);
  shiftScaleBy(src, val);
  parse(src);```

you can use one of these.

please raise questions if you need more help.

**Comment by OljasOmar** [comment]
Let me please write what I understand.

1. I need to load/import dist/chords.js
2. call function parse() and pass an argument to it.
My strings are returned by php function <?php the_content();?>
so, my code will be like:

```
<script>
var src = <?php the_content();?>;
parse(src);
shiftScaleBy(src, 3);
</script>
```

3. call a function shiftScaleBy(src, val); in order to transpose

Is that enough?

Thanks

**Comment by OljasOmar** [comment]
sample script i'm using:

```
<script>
function parse() {
            var src = <?php the_content();>;
            var dst = document.getElementById('my_content');
            dst.innerHTML = chords.parse(src);
        }
<div id="my_content"></div>
</script>
<script>
$(document).ready(function(){
     parse();
});

</script>
```

**Comment by nadunindunil** [comment]
Hi @OljasOmar , I think your last sample script should work if your content is in `src` variable (I doubt about the `var src = <?php the_content();>;`). Let me know if you need further clarifications.

**Comment by OljasOmar** [comment]
Good day!

Yeas, you were right. Last script worked with little modification. I wraped `<?php the_content();>` with id `<span id="src_id"><?php the_content();><span>` . Then got content by `document.getElementById('src_id').innerHTML;`. I could not get the content by `.value;` This parses and displays content as expected.

```
function parse() {
            val = 0;
            var src =  document.getElementById('src_id').innerHTML;
            var dst = document.getElementById('my_content');
            dst.innerHTML = chords.parse(String(src));
        }
```

However, transposer is not working like that:

```
        function shiftMinus() {
            val -= 1;
            var src = document.getElementById('src_id').innerHTML;
            var dst = document.getElementById('my_content');
            dst.innerHTML = chords.shiftScaleBy(src, val);
        }
```
It parses content and displays where 'my_content' tag is placed, but no transpose. 
Could you please tell me where i am doing it wrong?

Best wishes,

Oljas

**Comment by OljasOmar** [comment]
Good day!

Thank you! I managed to solve the issue.

Best wihes,

Oljas

**Comment by nadunindunil** [comment]
Hi @OljasOmar 
It was my pleasure.
please let me know your ideas and suggestion about the algorithm.

Thank you.
