### ISSUE TITLE
Transpose down -1 stops

### ISSUE THREAD

**Issue by angeloskalaitzakis** [Open-SL/Chords-Transposer#11]
When you transpose up +1 it circles through the chords it goes up to 12 semitones and starts over again. 
However when you transpose down -1 it stops after 13 semitones.

i have also modified your code and added some markdowns. etc
[tab]
e|---------------------------------------------------------------------------|
B|---------------------------------------------------------------------------|
G|---------------------------------------------------------------------------|
D|---------------------------------------------------------------------------|
A|---------------------------------------------------------------------------|
E|---------------------------------------------------------------------------|
[/tab]

[chorus]
This is a chorus
[/chorus]

[comment]
this is a comment
[/comment]

let me know if you want the code.

**Comment by nadunindunil** [comment]
This was fixed at #13
